#!/bin/bash
if [ $# -eq 0 ]
then
	echo "Empty argument, use --help to see available arguments"
elif [ $1 = "--start" ]
then
	echo "Starting Termux-x11..."
	termux-x11 :0 &>/dev/null & pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 &>/dev/null
	echo ""
	echo -e "Termux-x11 started"
	echo ""
	echo "Starting Wine-Desktop..."
	$PREFIX/bin/start-wine
	pkill -f "app_process / com.termux.x11"
elif [ $1 = "--update" ]
then
	cd ~/
	curl -o install https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/install && chmod +x install && ./install
elif [ $1 = "--uninstall" ]
then
	echo "Uninstalling Wine-Desktop..."
	proot-distro remove ubuntu &>/dev/null
	rm $PREFIX/bin/wine
	rm $PREFIX/bin/start-wine
	echo "Done!"
elif [ $1 = "--version" ]
then
        echo "22.07.23 (beta)"
elif [ $1 = "--help" ]
then
        echo "Wine-Desktop - preconfigured Ubuntu 22.04 rootfs with Box64, Box86, Wine Proton, DXVK and Adreno GPU drivers for Android"
	echo "Usage: Wine-Desktop {argument}"
	echo "Available arguments:"
	echo "--start - start Wine-Desktop"
	echo "--update - update Wine-Desktop"
	echo "--uninstall - uninstall Wine-Desktop (all data in rootfs will be clear)"
	echo "--version - show current version of Wine-Desktop"
	echo "--help - see available arguments"
else
	echo "Invalid argument, use --help to see available arguments"
fi
